import QuoteForm from "../quote-form";
import SiteNav from "../site-nav";
import SocialLinks from "../social-links";
import IndustryLogos from "../industry-logos";
import { Service, services } from "../service-data";

export default function ServicePage({ service }: { service: Service }) {
  const related = services.filter(item => item.slug !== service.slug).slice(0,3);
  return <main className="service-detail-page">
    <SiteNav quoteHref="#service-enquiry" />
    <section className="service-detail-hero"><div><div className="breadcrumb"><a href="/">Home</a><span>/</span><a href="/services">Services</a><span>/</span>{service.title}</div><div className="eyebrow"><span></span>{service.eyebrow}</div><h1>{service.headline}</h1><p>{service.description}</p><a className="button" href="#service-enquiry">Request a quote <span>→</span></a></div><aside><small>COMMERCIAL EPC DIRECT</small><strong>{service.title}</strong><div className="service-signal"><i></i><i></i><i></i><i></i><i></i></div><p>Accredited specialists.<br/>Clear reporting.<br/>Direct support.</p></aside></section>
    <IndustryLogos />
    <section className="section service-overview"><div><span className="kicker">About the service</span><h2>What is {service.title}?</h2></div><p>{service.overview}</p></section>
    <section className="service-facts"><div><span className="kicker light">Who it’s for</span><h2>Built around commercial property.</h2>{service.suitable.map(item=><p key={item}><span>✓</span>{item}</p>)}</div><div><span className="kicker light">What we consider</span><h2>A clear, professional assessment.</h2>{service.checks.map((item,index)=><p key={item}><span>0{index+1}</span>{item}</p>)}</div></section>
    <section className="section service-process"><div className="section-heading"><div><span className="kicker">How it works</span><h2>One in-house team, three clear steps.</h2></div><p>Our own team keeps the process moving and gives you one point of contact from the first property details to the final documentation.</p></div><div className="service-process-grid"><article><span>01</span><h3>Share the property</h3><p>Tell us the location, building type and what you need.</p></article><article><span>02</span><h3>Book the assessment</h3><p>Arrange a convenient visit with the appropriately qualified member of our in-house team.</p></article><article><span>03</span><h3>Receive the report</h3><p>{service.deliverable}</p></article></div></section>
    <section className="quote-section service-enquiry" id="service-enquiry"><div className="quote-copy"><span className="kicker">{service.title} enquiry</span><h2>Tell us about your property.</h2><p>Share a few details and we’ll confirm the right assessment, availability and a clear quotation.</p><div className="quote-promise"><span>✓</span><div><strong>No-obligation quote</strong><p>Review the details before booking.</p></div></div><div className="quote-promise"><span>✓</span><div><strong>Commercial specialists</strong><p>Matched to the property and service.</p></div></div></div><QuoteForm formLabel={`${service.title} details`} buttonLabel="Request my quote" sourceLabel={`${service.title} service page`} /></section>
    <section className="section related-services"><span className="kicker">Related services</span><div className="related-heading"><h2>More ways we can help.</h2><a href="/services">View all services →</a></div><div>{related.map((item,index)=><a key={item.slug} href={`/services/${item.slug}`}><span>0{index+1}</span><strong>{item.title}</strong><p>{item.menuCopy}</p><i>→</i></a>)}</div></section>
    <footer><a className="brand brand-footer" href="/"><span className="brand-mark" aria-hidden="true"><i></i><i></i><i></i></span><span>Commercial EPC <b>Direct</b></span></a><p>Commercial property assessments, made simple.</p><div className="footer-links"><a href="/services">Services</a><a href="/#faq">Guides</a><a href="/about">About</a><a href="/locations">Locations</a><a href="#service-enquiry">Get a quote</a></div><SocialLinks /><small>© {new Date().getFullYear()} Commercial EPC Direct. All rights reserved.</small></footer>
  </main>;
}
