import type { Metadata } from "next";
import QuoteForm from "../quote-form";
import SiteNav from "../site-nav";
import SocialLinks from "../social-links";
import IndustryLogos from "../industry-logos";

export const metadata: Metadata = {
  title: "Commercial EPC London | In-House Commercial EPC Assessors",
  description: "Commercial EPC assessments in London from our accredited in-house team. Offices, shops, warehouses and industrial units across Greater London.",
  alternates: { canonical: "/commercial-epc-london" },
  openGraph: { title: "Commercial EPC London | In-House Commercial EPC Assessors", description: "Commercial energy assessments across Central and Greater London.", url: "https://commercial-epc-direct.gradwell-gro-3352.chatgpt.site/commercial-epc-london", images: [{ url: "https://commercial-epc-direct.gradwell-gro-3352.chatgpt.site/og.png", width: 1731, height: 909, alt: "Commercial EPC Direct" }] },
};

const propertyTypes = ["Offices and office buildings", "Retail shops and parade units", "Warehouses", "Industrial units", "Workshops", "Business units", "Restaurants and cafés", "Pubs and hospitality", "Storage facilities", "Trade counters", "Mixed-use developments", "Larger commercial buildings"];
const centralAreas = ["City of London", "Bank", "Liverpool Street", "Moorgate", "Farringdon", "Holborn", "Bloomsbury", "Covent Garden", "Soho", "Mayfair", "Fitzrovia", "Marylebone", "Westminster", "Victoria", "Paddington", "King's Cross", "South Bank", "London Bridge"];
const assessmentFactors = ["Walls, roofs and floors", "Windows and glazing", "Heating systems", "Cooling and air conditioning", "Natural and mechanical ventilation", "Fixed lighting", "Building layout and zoning", "Hot water and controls"];
const sectors = [
  { number: "01", title: "London offices", copy: "Individual suites, business centres, converted offices and multi-storey buildings across the City, West End, Canary Wharf and emerging business districts.", items: ["Individual offices", "Office suites", "Business centres", "Mixed office and retail"] },
  { number: "02", title: "Shops and retail", copy: "High-street shops, parade units, showrooms, restaurants and customer-facing premises from the West End to local London centres.", items: ["High-street shops", "Retail units", "Showrooms", "Hospitality premises"] },
  { number: "03", title: "Warehouses", copy: "Warehouse and logistics assessments around Park Royal, Wembley, Enfield, Hayes, Southall, Barking, Dagenham and Croydon.", items: ["Distribution units", "Storage facilities", "Warehouse and office units", "Logistics property"] },
  { number: "04", title: "Industrial property", copy: "Light industrial, manufacturing, workshops and trade counters across London’s industrial estates and transport corridors.", items: ["Manufacturing premises", "Workshops", "Engineering units", "Trade counters"] },
];
const zones = [
  { title: "Central London", places: "City · Westminster · West End · South Bank", copy: "Modern offices, historic commercial buildings, retail, hospitality and complex mixed-use properties." },
  { title: "East London", places: "Canary Wharf · Shoreditch · Stratford · Barking", copy: "Offices, converted warehouses, retail, hospitality, workshops and industrial units." },
  { title: "South London", places: "Southwark · Brixton · Wimbledon · Croydon", copy: "Central office and hospitality premises through to shops, business units and industrial property." },
  { title: "West London", places: "Hammersmith · Ealing · Park Royal · Heathrow", copy: "Town-centre commercial property, business parks, warehouses, logistics and industrial estates." },
  { title: "North London", places: "Camden · Islington · Tottenham · Enfield", copy: "High-street shops and offices alongside workshops, warehouses and industrial units." },
];
const areas = ["City of London", "Westminster", "Canary Wharf", "Docklands", "Shoreditch", "Hackney", "Islington", "Camden", "King's Cross", "Paddington", "Hammersmith", "Ealing", "Park Royal", "Wembley", "Enfield", "Stratford", "Barking", "Dagenham", "Greenwich", "Southwark", "Brixton", "Croydon", "Wimbledon", "Richmond"];

export default function CommercialEpcLondon() {
  return <main className="location-page london-page">
    <SiteNav quoteHref="#london-top-enquiry" />
    <section className="location-hero" id="top">
      <div className="location-hero-copy">
        <div className="breadcrumb"><a href="/">Home</a><span>/</span><a href="/locations">Locations</a><span>/</span>Commercial EPC London</div>
        <div className="eyebrow"><span></span> Commercial energy assessors in London</div>
        <h1>Commercial EPC<br/><em>London.</em></h1>
        <p className="hero-intro">Professional Commercial Energy Performance Certificate assessments for offices, shops, warehouses, industrial units and other non-domestic property throughout London.</p>
        <div className="hero-actions"><a className="button" href="#london-top-enquiry">Get your London quote <span>→</span></a><a className="text-link" href="#london-services">Explore the service <span>↓</span></a></div>
        <div className="location-proof"><span>✓</span> Delivered directly by our accredited in-house assessors</div>
      </div>
      <aside className="london-coverage-card" aria-label="Commercial EPC coverage across London">
        <div className="london-card-head"><span>GREATER LONDON COVERAGE</span><b>LDN</b></div>
        <div className="london-roundel" aria-hidden="true"><i></i><strong>LONDON</strong><span></span><span></span><span></span><span></span></div>
        <div className="london-card-copy"><small>ONE IN-HOUSE TEAM</small><strong>Across the<br/><em>capital.</em></strong><p>Central · North · South · East · West · Greater London</p></div>
        <a href="#london-top-enquiry">Check your property <span>→</span></a>
      </aside>
    </section>

    <section className="benefit-strip location-benefits"><div className="benefit"><span>01</span><div><strong>Greater London coverage</strong><p>Central districts to outer London</p></div></div><div className="benefit"><span>02</span><div><strong>Property-specific pricing</strong><p>Based on size and complexity</p></div></div><div className="benefit"><span>03</span><div><strong>In-house assessors</strong><p>Our accredited commercial specialists</p></div></div></section>
    <IndustryLogos />
    <section className="quote-section top-enquiry" id="london-top-enquiry"><div className="quote-copy"><span className="kicker">Quick London EPC enquiry</span><h2>Get a quote for your property.</h2><p>Send the postcode and first line of the address. We’ll review the property and prepare a clear quotation.</p><div className="quote-promise"><span>✓</span><div><strong>Direct service</strong><p>Handled by our own team.</p></div></div><div className="quote-promise"><span>✓</span><div><strong>No obligation</strong><p>Review your quote before booking.</p></div></div></div><QuoteForm postcodePlaceholder="e.g. EC2R 8AH" formLabel="London property details" buttonLabel="Get my EPC quote" sourceLabel="Commercial EPC London — top form" /></section>

    <section className="section york-introduction"><span className="kicker">Commercial Energy Performance Certificates in London</span><div className="introduction-grid"><h2>One direct service for the capital’s varied property market.</h2><div><p>London combines modern office towers and major retail developments with Victorian shops, converted warehouses, industrial estates, hotels and mixed-use buildings.</p><p>From an individual commercial unit to a complex multi-zone building, the work is completed by an appropriately qualified member of our own in-house team—not a freelance network.</p><a className="inline-arrow" href="#london-top-enquiry">Request a London quote <span>→</span></a></div></div></section>
    <section className="epc-services" id="london-services"><div className="services-copy"><span className="kicker light">Commercial EPC services across London</span><h2>Offices and retail to logistics and industry.</h2><p>A Commercial EPC records a non-domestic building’s calculated energy performance and includes recommendations for potential improvement.</p><p>We work directly with landlords, property owners, businesses, managing agents and commercial property professionals.</p></div><div className="property-checklist">{propertyTypes.map((type, index) => <div key={type}><span>{String(index + 1).padStart(2, "0")}</span><strong>{type}</strong><i>✓</i></div>)}</div></section>

    <section className="section leeds-city-centre london-central"><div className="leeds-city-copy"><span className="kicker">Commercial EPC assessments in Central London</span><h2>From individual suites to complex landmark buildings.</h2><p>Central London’s commercial stock ranges from modern high-rise developments to historic properties that have been refurbished, converted or subdivided over time.</p><p>Send the address, approximate floor area and any available plans and our team will confirm the assessment scope.</p><a className="inline-arrow" href="#london-mid-enquiry">Request a central London quote <span>→</span></a></div><div className="leeds-district-grid">{centralAreas.map((area, index) => <div key={area}><span>{String(index + 1).padStart(2, "0")}</span><strong>{area}</strong></div>)}</div></section>
    <section className="leeds-sector-section london-sector-section"><div className="leeds-sector-heading"><span className="kicker light">London property expertise</span><h2>Commercial assessments across every major sector.</h2><p>Construction, use and installed services determine the assessment scope. Our in-house service accommodates straightforward premises and complex buildings.</p></div><div className="leeds-sector-grid">{sectors.map(sector => <article key={sector.title}><span>{sector.number}</span><h3>{sector.title}</h3><p>{sector.copy}</p><ul>{sector.items.map(item => <li key={item}>{item}</li>)}</ul></article>)}</div></section>

    <section className="section london-landmarks"><div className="section-heading"><div><span className="kicker">Major commercial districts</span><h2>The City, Canary Wharf, West End and Park Royal.</h2></div><p>Four distinct markets, each with its own building types, services and assessment considerations.</p></div><div className="london-landmark-grid"><article><span>01 / CITY</span><h3>City of London offices.</h3><p>From office suites around Bank, Moorgate and Liverpool Street to complete multi-storey buildings. Plans and building-services information help establish scope for larger properties.</p></article><article><span>02 / CANARY WHARF</span><h3>Modern commercial space.</h3><p>Corporate offices, retail, restaurants and mixed-use premises within larger developments, where precise demise information can be important.</p></article><article><span>03 / WEST END</span><h3>Converted and mixed-use.</h3><p>Offices, shops, restaurants and hospitality premises in older buildings with different uses, services and occupancy patterns.</p></article><article><span>04 / PARK ROYAL</span><h3>Industry and logistics.</h3><p>Warehouses, manufacturing, trade counters, workshops and office-and-warehouse combinations of widely varying size and complexity.</p></article></div></section>

    <section className="section london-zones"><div className="section-heading"><div><span className="kicker">Coverage by area</span><h2>Central, North, South, East and West London.</h2></div><p>One in-house service for individual properties and portfolios throughout Greater London.</p></div><div className="london-zone-grid">{zones.map((zone, index) => <article key={zone.title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{zone.title}</h3><small>{zone.places}</small><p>{zone.copy}</p></div></article>)}</div></section>

    <section className="assessment-section"><div className="assessment-heading"><span className="kicker light">What the assessment includes</span><h2>Building characteristics and fixed services.</h2><p>Our assessor gathers the information required to model the building using the approved non-domestic EPC methodology.</p></div><div className="factor-grid">{assessmentFactors.map((factor, index) => <div key={factor}><span>{String(index + 1).padStart(2, "0")}</span><strong>{factor}</strong></div>)}</div><p className="method-note">Layout and zoning are particularly relevant for London buildings containing combinations of office, retail, hospitality, warehouse, manufacturing or storage space.</p></section>
    <section className="section leeds-compliance-section"><div className="leeds-compliance-heading"><span className="kicker">Commercial EPC requirements</span><h2>Know when a certificate may be required.</h2><p>Requirements depend on the building and circumstances, and exemptions can apply. Seek appropriate professional or legal advice where there is uncertainty.</p></div><div className="leeds-compliance-grid"><article><span>01</span><h3>Construction, sale or letting</h3><p>An EPC is generally required when an applicable non-domestic property is constructed, sold or let to a new tenant, subject to exemptions.</p><ul><li>New construction</li><li>Commercial sale</li><li>New letting</li></ul></article><article><span>02</span><h3>Normally valid for 10 years</h3><p>A certificate is normally valid for 10 years or until replaced by a newer EPC. Existing certificates can be checked on the government register.</p><a href="https://www.gov.uk/find-energy-certificate" target="_blank" rel="noreferrer">Check the EPC register ↗</a></article><article><span>03</span><h3>Ratings and MEES</h3><p>Commercial EPCs use an A+ to G scale. Privately rented non-domestic properties covered by MEES generally need an E rating or above unless a valid exemption applies.</p><a href="https://www.gov.uk/guidance/non-domestic-private-rented-property-minimum-energy-efficiency-standard-landlord-guidance" target="_blank" rel="noreferrer">Read government guidance ↗</a></article></div></section>
    <section className="leeds-process-section london-process-section"><div><span className="kicker light">How to get a Commercial EPC in London</span><h2>Four clear steps.</h2><p>Floor plans and existing building information are especially useful for larger, subdivided or multi-storey properties.</p></div><ol><li><span>01</span><div><h3>Send the property details</h3><p>Provide the address, floor area, current use and required timescale.</p></div></li><li><span>02</span><div><h3>Receive your quotation</h3><p>Our team reviews the information and confirms the price and scope.</p></div></li><li><span>03</span><div><h3>Arrange site access</h3><p>Access is coordinated for our in-house assessor to inspect the property.</p></div></li><li><span>04</span><div><h3>Assessment and lodgement</h3><p>The building is modelled and the EPC produced and lodged where required.</p></div></li></ol></section>

    <section className="quote-section middle-enquiry" id="london-mid-enquiry"><div className="quote-copy"><span className="kicker">Working to a London property deadline?</span><h2>Tell us when you need it.</h2><p>If the EPC supports a sale, letting or marketing deadline, include the date and we’ll advise on our team’s availability.</p><div className="quote-promise"><span>✓</span><div><strong>Property-specific price</strong><p>Based on the building and scope.</p></div></div><div className="quote-promise"><span>✓</span><div><strong>Portfolio support</strong><p>For one property or several.</p></div></div></div><QuoteForm postcodePlaceholder="e.g. W1K 1AA" formLabel="London assessment enquiry" buttonLabel="Request availability" sourceLabel="Commercial EPC London — middle form" /></section>
    <section className="york-areas" id="london-areas"><div className="areas-copy"><span className="kicker light">Commercial EPC coverage across London</span><h2>Throughout the capital and Greater London.</h2><p>Our team handles single commercial units, large buildings and portfolios across all parts of London.</p><div className="why-choose"><strong>Why choose Commercial EPC Direct?</strong><ul><li>Our own accredited in-house assessors</li><li>No freelance assessor network</li><li>Experience across building types</li><li>Single and portfolio instructions</li></ul></div><a className="button button-light" href="#london-quote">Check your property <span>→</span></a></div><div className="area-list">{areas.map((area, index) => <div key={area}><span>{String(index + 1).padStart(2, "0")}</span><strong>{area}</strong><i>↗</i></div>)}</div></section>
    <section className="quote-section york-quote" id="london-quote"><div className="quote-copy"><span className="kicker">Get a Commercial EPC quote in London</span><h2>Tell us about your property.</h2><p>Send the postcode, first line of the address and your contact details. We’ll review the building and prepare a quotation.</p><div className="quote-promise"><span>✓</span><div><strong>Accurate quotation</strong><p>Based on the property and scope.</p></div></div><div className="quote-promise"><span>✓</span><div><strong>Direct delivery</strong><p>By our own in-house team.</p></div></div></div><QuoteForm postcodePlaceholder="e.g. E14 5AB" sourceLabel="Commercial EPC London — bottom form" /></section>

    <section className="section faq" id="london-faq"><div className="faq-title"><span className="kicker">Commercial EPC London FAQs</span><h2>Useful answers before you book.</h2></div><div className="faq-list">
      <details><summary>How much does a Commercial EPC cost in London?<span>+</span></summary><p>The cost depends on the property’s size, type and complexity. Send the postcode and address for a tailored quotation.</p></details>
      <details><summary>How quickly can I get a Commercial EPC in London?<span>+</span></summary><p>Timescales depend on our in-house team’s availability and the building’s complexity. Tell us if you are working towards a deadline.</p></details>
      <details><summary>How long is a Commercial EPC valid?<span>+</span></summary><p>Commercial EPCs are generally valid for 10 years, or until replaced by a newer certificate.</p></details>
      <details><summary>Who can produce a Commercial EPC?<span>+</span></summary><p>The assessment must be completed by an appropriately qualified and accredited Non-Domestic Energy Assessor.</p></details>
      <details><summary>Do you cover Central London and the City?<span>+</span></summary><p>Yes. Our in-house assessors cover offices, retail and other commercial premises across Central London and the City.</p></details>
      <details><summary>Do you provide Commercial EPCs in Canary Wharf?<span>+</span></summary><p>Yes. We cover applicable commercial properties throughout Canary Wharf, Docklands and surrounding areas.</p></details>
      <details><summary>Can you provide EPCs for London warehouses?<span>+</span></summary><p>Yes. Our team assesses warehouses, distribution units and storage facilities throughout Greater London.</p></details>
      <details><summary>Do you cover Park Royal?<span>+</span></summary><p>Yes. We assess warehouses, industrial units, workshops, manufacturing premises and other commercial buildings in Park Royal.</p></details>
      <details><summary>Can you assess London shops and offices?<span>+</span></summary><p>Yes. Our service covers individual offices, office buildings, shops, retail units, restaurants and other commercial premises.</p></details>
      <details><summary>Do you cover all London boroughs?<span>+</span></summary><p>Our service covers Greater London. Send the property postcode and we’ll confirm coverage and availability.</p></details>
      <details><summary>Can you coordinate several properties?<span>+</span></summary><p>Yes. Send us the addresses and available property information and our in-house team can review a London portfolio.</p></details>
    </div></section>
    <footer><a className="brand brand-footer" href="/"><span className="brand-mark" aria-hidden="true"><i></i><i></i><i></i></span><span>Commercial EPC <b>Direct</b></span></a><p>Commercial energy assessments, made simple.</p><div className="footer-links"><a href="/">Home</a><a href="#london-services">Services</a><a href="#london-faq">Guides</a><a href="/about">About</a><a href="/locations">Locations</a><a href="#london-quote">Get a quote</a></div><SocialLinks /><small>© {new Date().getFullYear()} Commercial EPC Direct. All rights reserved.</small></footer>
  </main>;
}
