export type Service = { slug:string; title:string; menuCopy:string; eyebrow:string; headline:string; description:string; overview:string; suitable:string[]; checks:string[]; deliverable:string };

export const services: Service[] = [
  { slug:"commercial-epc", title:"Commercial EPC", menuCopy:"Energy ratings for non-domestic property", eyebrow:"Commercial energy assessment", headline:"Commercial EPCs, handled directly.", description:"Accredited commercial energy assessments for offices, shops, warehouses and other non-domestic properties.", overview:"A Commercial Energy Performance Certificate records a building’s energy efficiency and provides recommendations for improvement. Our accredited in-house assessors complete the site visit, assessment and certificate directly.", suitable:["Selling or letting commercial property","Renewing an existing certificate","New or refurbished buildings","Single sites and property portfolios"], checks:["Building fabric and construction","Heating and cooling systems","Lighting and ventilation","Glazing, insulation and controls"], deliverable:"A completed commercial EPC and recommendation report, lodged where required." },
  { slug:"tm44-inspection", title:"TM44 Inspection", menuCopy:"Air-conditioning energy assessments", eyebrow:"Air-conditioning inspection", headline:"TM44 inspections without the uncertainty.", description:"Professional air-conditioning energy assessments for commercial systems, with clear findings and practical recommendations.", overview:"A TM44 inspection reviews the energy efficiency and operation of qualifying air-conditioning systems. The assessment is completed directly by an appropriately qualified member of our in-house team, from booking to report.", suitable:["Offices and managed workspaces","Retail and hospitality premises","Public and institutional buildings","Multi-site property portfolios"], checks:["System condition and maintenance","Controls and operating settings","Sizing and usage patterns","Energy-saving opportunities"], deliverable:"A clear TM44 inspection report with observations and efficiency recommendations." },
  { slug:"eicr", title:"EICR", menuCopy:"Electrical installation condition reports", eyebrow:"Electrical safety reporting", headline:"Commercial EICRs, clearly coordinated.", description:"Electrical Installation Condition Reports for commercial premises, carried out by our competent in-house electrical professionals.", overview:"An EICR assesses the condition of a property’s fixed electrical installation. Our own team identifies damage, deterioration and defects that may require attention, helping duty holders understand the condition of the installation.", suitable:["Commercial landlords","Offices, shops and hospitality","Industrial and warehouse property","Portfolio and facilities managers"], checks:["Fixed wiring and circuits","Protective devices and earthing","Visible damage or deterioration","Items requiring remedial attention"], deliverable:"An Electrical Installation Condition Report recording observations and classification codes." },
  { slug:"floor-plans", title:"Floor Plans", menuCopy:"Clear measured plans for commercial space", eyebrow:"Commercial measured plans", headline:"Floor plans made clear and usable.", description:"Professional floor plans for commercial sales, lettings, management and property documentation, completed by our in-house team.", overview:"Our in-house floor plan service turns an on-site survey into a clear visual record of the property layout. Plans can support marketing, management and wider property projects.", suitable:["Sales and letting particulars","Lease and property records","Space planning projects","Portfolio documentation"], checks:["Room arrangement and circulation","Doors, access and key features","Overall layout and floor levels","Property-specific plan requirements"], deliverable:"A clean digital floor plan supplied in an agreed, practical format." },
  { slug:"legionella", title:"Legionella", menuCopy:"Water hygiene risk assessments", eyebrow:"Water hygiene assessment", headline:"Legionella risk assessments, properly organised.", description:"Practical Legionella risk assessments for commercial and managed properties, with clear findings and actions.", overview:"A Legionella risk assessment considers water systems and the conditions that may allow Legionella bacteria to grow or spread. A competent member of our in-house team completes the assessment and provides a clear record of findings.", suitable:["Commercial landlords","Offices and workplaces","Hospitality and managed accommodation","Property and facilities managers"], checks:["Hot and cold water systems","Temperatures and water storage","Little-used outlets and stagnation","Management controls and records"], deliverable:"A written Legionella risk assessment with identified risks and recommended control actions." },
  { slug:"display-energy-certificate", title:"Display Energy Certificate", menuCopy:"Operational energy ratings for public buildings", eyebrow:"Operational energy certification", headline:"Display Energy Certificates, made straightforward.", description:"DECs and advisory reports for qualifying buildings occupied by public authorities or frequently visited by the public.", overview:"A Display Energy Certificate shows the operational energy performance of a building based on actual energy use. Our in-house team gathers the required information, completes the assessment and provides the finished documentation.", suitable:["Public authority buildings","Schools and education premises","Healthcare and community buildings","Multi-building public estates"], checks:["Recorded energy consumption","Building use and floor area","Operational patterns","Potential efficiency improvements"], deliverable:"A Display Energy Certificate and accompanying advisory report where applicable." },
];

export const serviceBySlug = Object.fromEntries(services.map(service => [service.slug, service])) as Record<string, Service>;
